load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")
load(
    "@root//rules/js:toolchain.bzl",
    "js_default_runtime",
    "system_bun_toolchain",
    "system_deno_toolchain",
    "system_node_toolchain",
)

system_demo_toolchains()

system_node_toolchain(
    name = "node",
)

system_bun_toolchain(
    name = "bun",
)

system_deno_toolchain(
    name = "deno",
)

js_default_runtime(
    runtime = ":node_info",
)