load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")
load("@root//rules/js:toolchain.bzl", "system_node_toolchain")

# All the default toolchains, suitable for a quick demo or early prototyping.
# Most real projects should copy/paste the implementation to configure them.
system_demo_toolchains()

system_node_toolchain(
    name = "node",
)