load("//rules/js:js_test.bzl", "js_test")
load("//rules/js:js_run.bzl", "js_run")

js_run(
    name = "start",
    entry = "server.ts",
    js_runtime = "toolchains//:deno_info",
    srcs = ["server.ts"],
)

js_test(
    name = "test",
    entry = "server.test.ts",
    js_runtime = "toolchains//:deno_info",
    srcs = ["server.test.ts", "server.ts"],
)
