load("//rules/js:js_test.bzl", "js_test")
load("//rules/js:js_run.bzl", "js_run")

js_run(
    name = "start",
    entry = "server.js",
    js_runtime = "toolchains//:bun_info",
    srcs = ["server.js"],
)

js_test(
    name = "test",
    entry = "server.test.js",
    js_runtime = "toolchains//:bun_info",
    srcs = ["server.test.js", "server.js"],
)
